---
title: "Assignment_2"
format: html
editor: visual
---

# Assignment 2: Cross-Sectional Estimates

The objective of this assignment is to explore the relationship between regional development and inequality by utilizing cross-sectional estimation techniques, focusing on data from the year 2010.

## Part A: Growth and Inequity

In the first part, we will dive into growth and inequity.
First, we will estimate a simple linear regression model looking at the relationship between regional development and regional inequality.
Further, we will define our model specifications, justify variable selection, and explain the expected relationship.
Then, we will assess the goodness of fit of our model through different statistical measures.
We will discuss the reliability and validity of the estimated model and discuss if the classical OLS assumptions hold.
Lastly, we will visualize our model in a plot with a fitted regression line.

### Model Estimation

### Model Diagnostics

### Visualization

## Part B: Exploring Other Determinants of Inequity

In the second part, we will explore three other potential determinants that we hypothesize may influence regional inequity.
First, an explanation of the data acquisition will be given.
Further, we will estimate a multiple linear regression model incorporating the newly selected variables alongside regional development, with regional inequality.
Then, we will define our model specifications and clarify why we expect the selected variables to influence regional inequality.
Lastly, we will interpret the estimated coefficients, reflect on the overall fit of the model, and discuss the contribution of each variable to explaining variations in regional inequality.

### Multiple Linear Regression Model

### Model Interpretation
