---
title: "Assignment_1"
format: html
editor: visual
---

```{r}
#| label: setup
#| echo: false
#| output: false
#| message: false
library(tidyverse)
library(readxl)
library(magrittr)
```

# Part A: Sub-national GDP and GDP per Capita

## Data Acquistion

```{r}
gdp_data <- read_csv("nama_10r_3gdp__custom_7667248_linear.csv") 
```

```{r}
population_data <- read_csv("demo_r_pjanaggr3__custom_7667383_linear.csv")
```

```{r}
GDP_UK <- read_excel("regionalgrossdomesticproductgdpallitlregions.xlsx", 
    sheet = "Table 5", skip = 1)
```

```{r}
Population_UK <- read_excel("regionalgrossdomesticproductgdpallitlregions.xlsx", 
    sheet = "Table 6", skip = 1)
```

```{r}
gdp_data <- gdp_data |>
  select(TIME_PERIOD, geo, OBS_VALUE)
```

```{r}
population_data <- population_data |>
  select(TIME_PERIOD, geo, OBS_VALUE)
```

```{r}
GDP_UK <- read_excel("regionalgrossdomesticproductgdpallitlregions.xlsx", 
    sheet = "Table 5", skip = 1)
```

```{r}
Population_UK <- read_excel("regionalgrossdomesticproductgdpallitlregions.xlsx", 
    sheet = "Table 6", skip = 1)
```

```{r}
# Read the entire data from Excel
GDP_UK <- GDP_UK %>%
  gather(year, gdp, -ITL, -`ITL code`, -`Region name`) %>%
  filter(ITL == "ITL3") %>%
  mutate(geo = `ITL code`) %>%
  select(year, geo, gdp)
```

```{r}
Population_UK <- Population_UK %>%
  gather(year, pop, -ITL, -`ITL code`, -`Region name`) %>%
  filter(ITL == "ITL3") %>%
  mutate(geo =`ITL code`) %>%
  select(year, geo, pop)
```

\
GDP_data_UK_pop \<- read_excel("regionalgrossdomesticproductgdpallitlregions.xlsx",\
sheet = "Table 6", skip = 1) %\>%\
gather(year, pop, -ITL, -\`ITL code\`, -\`Region name\`) %\>%\
filter(ITL=="ITL3") %\>%\
mutate(geo=\`ITL code\`) %\>%\
select(geo,year,pop)

## GDP per Capita Calculation

## Descriptive Analysis

# Part B: Regional Inequity

## Literature Review

## Gini Coefficient Calculation

## Data Presentation

## Discussion
