---
title: "Regional development and inequality"
format: pdf
editor: visual
bibliography: MSB104.bib
---

Western Norway University of Applied Sciences\
MSB104 Econometrics\
Hanna Sundal Bjerkreim & Elvar Solheim

```{r}
#| label: setup
#| echo: false
#| output: false
#| message: false
library(tidyverse)
library(readxl)
library(magrittr)
library(knitr)
library(dineq)
library(ineq)
library(ggplot2)
library(scales)
library(cowplot)
library(dplyr)
library(huxtable)
library(vtable)
library(future)
library(furrr)
library(lmtest)
library(plm)
```

# I. Introduction

## Background

Regional development, a cruical component of economic growth, represents a collective effort to enhance well-being and living standards in specific geographic areas, playing a vital role in contributing to national performance and fostering resilient and inclusive societies [@oecd].
As regions navigate the intricate dynamics of growth, decline, and adaptation, a multitude of economic, social, and environmental outcomes emerges [@pike2016].
These variations give rise to the concept of regional inequality - a phenomenon rooted in the uneven distribution of resources, opportunities, and development across different regions.
Regional inequality posting a fundamental challenge for human society, a central focus of academic research, and a major concern of governments [@wei2015].
There has been a long-lasting debate about the scope, dimensions, trajectory, mechanisms, and consequences of regional inequality, along with the policies that address disparity [@wei2015].
We should care about regional inequality because it is essential for both the economy and social welfare in general.
The potential consequences of regional inequality are many, and when certain regions experience higher levels of economic development and prosperity compared to others, it can have far-reaching consequences.
@lessmann2017 highlights a correlation between regional inequality and personal income inequality, ethnic inequality, and political stability.
These consequences underline the importance of addressing regional imbalances within countries, as they may independently contribute to economic outcomes and exacerbate issues such as income inequality, ethnic tensions, and segregation.

Given this context, this paper delves into the intricate dynamics of regional development and inequality within a subset of European countries.
The subset comprises the Czech Republic, Turkey, Finland and the United Kingdom.
Analysing these countries provides a nuanced understanding of regional development and inequality, offering insights into potential policy interventions aimed at fostering more balanced and inclusive development pathways.

## Objectives

Throughout the semester in our econometrics course, we completed three distinct assignments, each contributing to a comprehensive understanding of regional development and inequality within the Czech Republic, Turkey, Finland and the United Kingdom.

The primary objective of the first assignment was to acquire, process, and analyse sub-national GDP and population data, aiming to answer questions about regional economic disparities.
This involved calculating GDP per capita and the population-weighted GDP Gini coefficient, and exploring regional inequality through descriptive statistics and visualizations.

In the second assignment, the objective shifted towards investigating the relationship between regional development and inequality for the year 2010.
We delved into questions regarding the nature of this relationship, utilizing cross-sectional estimation techniques.
Starting with simple linear regression, we explored the initial relationship and expanded our analysis by introducing potential determinants through multiple linear regression.

In the third assignment, our aim was to explore alternative function forms, specifically logarithmic and quadratic, as well as implementing panel estimates to scrutinize the relationship between regional development and inequality.
We compared the alternative models and the panel estimates with the cross-sectional estimates obtained earlier.

Synthesizing the critical findings from Assignments 1, 2, and 3, this paper aims to provide a cohesive understanding of regional development and inequality within the specified countries.
By shedding light on the complexities of this issue and answering these specific research questions, we aim to offer valuable insights that can help policy-making and practice in the realm of regional development and inequality.

## Significance

The exploration of regional development and inequality within the context of the Czech Republic, Turkey, Finland and the United Kingdom reveals important insights into the dynamics of economic growth and diparities at regional levels.

In a time characterized by increasing interconnectedness, understanding the intricacies of regional development is imperative.
Regional development not only shapes the well-being and living standards of regions but also plays a crucial role in bolstering national performance.
The findings from this research not only contribute to the specific knowledge of the Czech Republic, Tureky, Finland and the United Kingdom, but also provides information for understanding regional disparities globally.
By identifying patterns of regional development and inequality within these specific countries, this study offers a valuable understanding that can be applied to similar challenges faced by nations globally.

Furthermore, this research provides valuable insights that can guide policy-makers, economists, and social scientists.
The uneven distribution of resources, opportunities, and development underscores the importance of addressing these issues, especially as the impacts of regional inequality are more pronounced than ever.
The pressing concern of regional inequality highlights the necessity for a nuanced analysis to inform targeted policies and initiatives.
Policies promoting balanced growth and mitigating disparities among regions take on heightened relevance in the current global context.

This research not only expands the understanding of regional dynamics but also equips with the knowledge needed for more balanced and inclusive development pathways, fostering a more equitable global future.

# II. Literature Review

## Previous Work

The Kuznets curve has been one of the most debated hyphotesis in development economics.
Orignally, @kuznets1955 introduced this curve to illustrate the relationship between per capita income and income inequality.
The hypothesis says that income inequality should follow an inverted U-shape along the development process, where it first increases, then peaks, and then decreases.
This hypothesis may also apply to regional inequality.
The idea is that the development in extremely poor economies, typically starts in one part of the country, leading to these regions become richer than the rest.
Consequently, regional inequality rise at low levels of development.
A higher level of development, the less developed regions catch up, fostering a convergence process [@lessmann2017].
There is empirical evidence for the inverted U-shape in regional inequality, for example @barrios2009 study of the dynamics of regional inequalities.
@lessmann2017 also find strong support for the inverted-U, as well as evidence that regional inequality is increase again at very high levels of development.

In general are the empirical studies on regional inequality is limited to a specific country sample with a general bias towards medium and high income economies.
This is a issue when investigating the upward sloping part of the Kuznets curve.
The challenge is obtaining data from the less developed regions in the world.
The poorest regions appear as blank spots on the map.
@lessmann2017 fill this research gap by predicting regional incomes using satellite night-time light data for the countries with no reliable statistical data available.
The higher night-time light intensity, the higher level of economic activity.
The data on the very poorest countries allowed @lessmann2017 to estimate the upward sloping part of the Kuznets curve in regional inequalities.
They found that the relationship between regional development and regional inequality follow a pattern similar to a N-shape.
By examining changes in inequality over time, @lessmann2017 found that the majority of all countries experience sigma convergence, which means that regional inequality decreases over time.
However, they found that some poor and lower-middle-income countries, along with some rich economies, show divergence.
This shows that very poor countries exhibit increasing inequalities, while most middle- and high-income countries show decreasing or stabilizing inequalities.
Interestingly, regional inequalities increase again in the richest countries, forming the right side of the N-shaped pattern [@lessmann2017].

## Research Gap

The literature review highlighted the significance of the Kuznets curve in development economics and brought attention to a research gap in the litterature.
Empirical studies on regional inequality seems to often be limited to specific country sample with a general bias towards medium and high-income economies.
This limitation poses a challenge when exploring the ascending part of the Kuznets curve, as obtaining data from less developed regions are difficult.

In this paper we aim to help cover this gap in the literature, by exploring the relationship between regional development and inequality within a subset of European countries, providing insights into the dynamics of regional inequality in a diverse set of countries, which include both medium to high and lower-income regions.
The inclusion of this particular set of countries gives our research a distinctive character, offering a unique combination for comparisons.
The study allowing a nuanced exploration of regional development and inequality within the specific context of the Czech Republic, Turkey, Finland, and the United Kingdom.

# III. Data and Methodology

## Data Sources

In the assignments, the primary data sources used were Eurostat and the Office for National Statistics (ONS).
Eurostat provided sub-regional data on GDP and population for the EU countries (Czech Republic, Turkey and Finland).
For the United Kingdom, which is not a part of the EU, ONS supplied sub-regional GDP and population data.
The datasets we downloaded from Eurostat included regions at a NUTS3 level.
Following Brexit, the ONS developed a domestic statistical classification framework separate from NUTS, refferd to as International Territorial Levels (ITLs).
This system aligns with the NUTS classification, enabling comparability.
The dataset downloaded from ONS included regions at a ITL3 level, which corresponds to the NUTS3 level.
Some manipulations of the raw data was necessary to obtain comparable value.
The datasets from Eurostat and ONS were merged to one main dataset containing GDP and population data at a NUTS3-level for the years 2000 to 2020.
The main dataset is based on 4 countries and 294 NUTS3 regions.
Later we generated another dataset for the NUTS2 regions.
The dataset includes GDP measured at current market prices in millions of euros for Czech Republic, Turkey, and Finland.

Later in the analysis we included three potential determinants of regional inequality alongside regional development, for the NUTS2 regions in Turkey for the year 2010.
Eurostat was the source for the additional data on unemployment, infrastructure, and life expectancy.

Limitations may arise from variations in data collection methods between Eurostat and ONS, as well as potential differences in classification systems between the EU and the United Kingdom.
The shift from the NUTS to the ITL classification system for the United Kingdom after Brexit, introduces a potential limitation.
While efforts are made to align the two classification systems, differences or uncertainties may still exist.
Even with efforts to align ITLs with NUTS, there might be subtle differences that could affect the comparability of data between the United Kindom and the other EU countries.\
The difference in currency units in the GDP data between the EU countries (million euros) and the United Kingdom (million pounds) introduces a source of complexity.
This should have been taken care of in the data manipulation, which was not done.

## Methodological Approach

We initiated our analysis by computing GDP per capita, serving as a measure for Regional development, and the population-weighted GDP Gini coefficient as a measure of regional inequality.
Subsequently, we conducted cross-sectional estimates, including a simple linear regression model and a multiple linear regression model.
Further, we explored alternative forms, incorporating a logarithmic model and a quadratic model.
Lastly, we extended our analysis to panel estimates.

### Regional development measure

We used GDP per capita as a measure of regional development.
GDP per capita gives an average representation of the economic well-being of the individuals, indicating the amount of economic output generated, by each person.
A higher GDP per capita indicates greater economic prosperity.
GDP per capita is good measure for assessing regional development, because it provides an indicator of the overall living standard in each region.
Additionally, GDP per capita is widely used and easily comparable across regions and countries.
We computed the GDP per capita for each sub-region using the formula: $y_{i} = \frac{GDP_{i}}{Population_{i}}$.

For the United Kingdom, GDP is measured at current market prices in millions of pounds.
The population variable represents the total annual population within each sub-region.
Consequently, the GDP per capita variable expresses GDP in millions of euros/pounds per capita in each sub-region.
In the regression models the GDP per capita is multiplied with 100.
The scaling helps make the numbers more manageable and interpretable in the context of the regression analysis.

### Regional inequality measure

Measuring regional inequality is challenging because it is difficult to compare regions of different sizes.
To deal with this issue, we use a population-weighted Gini coefficient that accounts for regions of different sizes.
This measure offers a way to assess the degree of regional inequality, allowing for comparison across regions and countries.
The population-weighted is chosen for measuring regional inequality, because it gives a nuanced view of regional inequality considering both GDP disparities and the population size in each region.
The population-weighted GDP Gini coefficient for each sub-region was computed by using the formula: $GINW_j=\frac{1}{2\overline y j} \sum_{i}^{n_j} \sum_{l}^{n_j} \frac{p_i}{P_j} \frac{p_l}{P_j} |y_i - y_l|$.

### Cross-sectional estimates

#### Simple Linear Regression

To see how regional development affects regional inequality we estimated a simple linear regression model with the population-weighted GDP Gini coefficient ($GINIW_j$) as the dependent variable and the GDP per capita ($y_j$ ) as the independent variable.
For the estimation we used a subset including only observations on NUTS 2 regions from the year 2010.
We estimated three models for a better insight into how the relationship between regional inequality and regional development is in the different countries.
The first model included data from all our countries, the second model focused only on EU countries, while the third model was all about the United Kingdom.
We dedicate a separate model to the United Kingdom, since the country accounted for almost half of the observations in our dataset.
Below is the equation for our simple linear regression model: $\hat{GINIW_{2010}} = \hat{\beta}_0 + \hat{\beta}_1 y_{2010}$.

Regression table

#### **Multiple Linear Regression**

We estimated a multiple linear regression model incorporating unemployment, infrastructure and life expectancy alongside regional development, as potential determinants of regional inequality.
We estimated this for the NUTS 2 regions in Turkey for the year 2010.
While the United Kingdom has the overall highest number of observations in our sample, sourcing data on various determinants was challenging.
Consequently, we opted to delve deeper into Turkey, the country with the second-highest number of observations.
With the population-weighted GDP Gini coefficient ($GINIW_j$) as the dependent variable and the GDP per capita ($y_j$ ), unemployment (${Unemployment}_{2010}$), life expectancy (${Life Expectancy}_{2010}$) and infrastructure (${Infrastructure}_{2010}$) as the independent variables we estimated this multiple linear model:$\hat{GINIW_{2010}} = \hat{\beta}_0 + \hat{\beta}_1 y_{2010} + \hat{\beta}_2 \text{Unemployment}_{2010} + \hat{\beta}_3 \text{Life Expectancy}_{2010} + \hat{\beta}_4 \text{Infrastructure}_{2010}$.

Regression table

### Alternative functional forms

We explored functional forms for the EU countries and the United Kingdom.
Since the number of observations for each of the EU-countries are small, we will stick to a model with all the EU countries together.
We will estimate a logarithmic model for the EU countries, and a quadratic model for the United Kingdom.

The logarithmic form suits models where diminishing returns or asymptotic behaviour is expected.
In our simple linear regression model for the EU countries we have a negative relationship where higher levels of regional development are associated with lower levels of inequality.
We therefore chose a logarithmic model for the EU countries.
The logarithmic model is: $\hat{GINIW_{2010}} = \hat{\beta}_0 + \hat{\beta}_1  log(y_{2010})$.

The quadratic form is used in situations where there is a curvature relationship between variables.
We think a quadratic from is suitable for the UK, because we expect an inverted U-shape, like the Kuznest curve.
Th quadratic model is: $\hat{GINIW_{2010}} = \hat{\beta}_0 + \hat{\beta}_1 y_{2010} + \hat{\beta}_2 y_{2010}^2$.

Regression table

### Panel estimates

# IV. Empirical Findings

## Cross-sectional Estimates

*Summarize essential results obtained from the cross-sectional analysis in Assignment 2.*

## Alternative Functional Forms and Panel Estimates

*Present the key insights derived from exploring alternative functional forms and panel estimates in Assignment 3.*

# V. Discussion

## Key Insights

*Synthesize and discuss the central insights emerging from the empirical findings.*

## Policy Implications

*Deliberate on the potential implications of your results for policy-making and practice in the realm of regional development and inequality.*

# VI. Limitations and Future Research

## Research Limitations

*Acknowledge any constraints or limitations encountered during your analysis.*

# VII. Conclusion

## Summary

*Provide a succinct summary of the main findings and their significance.*

## Final Reflections

*Briefly reflect on the research process and the contributions of your study to the field of regional development and inequality.*

# VIII. References
